services:
# --- DATABASE SERVICE (MYSQL) ---

  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - library-network
    

  mysql:
    image: mysql:8.4
    container_name: library-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

# --- API SERVICE (PHP) ---
  app:
    environment:
      - APP_KEY=base64:TB1M856sj05rDB9xf51ptWL03l7XQ4lvkuIQDbWkH54=
      - APP_ENV=local
      - APP_DEBUG=true
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/usr/src/library-api
    container_name: library-app
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - library-network

# --- WEB SERVER SERVICE (NGINX) ---
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: library-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  db_data: {}
  jenkins_home: {}